### ISSUE TITLE
Header file missing from build?

### ISSUE THREAD

**Issue by ITSPaul** [SWI-Prolog/contrib-swiplcs#8]
Hi I'm using VS 2019 targeting the latest Windows 10 SDK.

I have forked and cloned the repository when I build the solution

 I get the following error
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "include/SWI-Stream.h"	CalcStreamSize	..\contrib-swiplcs\CalcStreamSize\Main.cpp	36	

It appears the header file is missing from the distrbution?

**Comment by JanWielemaker** [comment]
SWI-Stream.h is part of the SWI-Prolog distribution (as well as SWI-Prolog.h).

**Comment by ITSPaul** [comment]
OK. Thanks, Jan. VS wouldn't find the Environment Path variable. But I was able to map directly to the include folder. However, I'm still getting a linker error.
Any ideas?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'C:\Program Files\swipl\bin\libswipl.dll.akernel32.lib'	CalcStreamSize	\contrib-swiplcs\CalcStreamSize\LINK	1

**Comment by JanWielemaker** [comment]
Doesn't ring a bell. Surely, names like CalcStreamSize() do not appear in the SWI-Prolog sources.  I doubt someone involved in this interface listens here.  You may try the forum.  Actually, you may search it as I vaguely recall there have been messages about this interface.
